PruebaMvc/Controllers/OfertaController.cs
using PruebaMvc.DAL;
using PruebaMvc.ModelsService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaMvc.Controllers
{
    public class OfertaController : Controller
    {
        OfertaDALServicio ofertaDALServicio = new OfertaDALServicio();

        #region Experimento

        public ActionResult Index()
        {
            List<OfertaS> oferta = new List<OfertaS>();

            return View("~/Views/Oferta/ConsultarOferta.cshtml", oferta.AsEnumerable());
        }

        public ActionResult ConsultarOfertaId(int idOferta)
        {
            OfertaS oferta = new OfertaS();

            try
            {
                oferta = ofertaDALServicio.obtenerOfertaId(idOferta.ToString());
            }
            catch(Exception ex)
            {
                ViewBag.Message = "Hubo un error al consultar el oferente. " + ex.Message;
            }
            return View("~/Views/Oferta/oferta.cshtml", oferta);
        }

        public ActionResult ConsultarTodasOferta(string tipoControl, string valor)
        {
            List<OfertaS> oferta = new List<OfertaS>();

            try
            {
                switch(tipoControl)
                {
                    case "1":
                        oferta = ofertaDALServicio.obtenerOfertaOferente(valor);
                        break;
                    case "2":
                        oferta = ofertaDALServicio.obtenerListaOferta();
                        break;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Hubo un error al consultar el oferente. " + ex.Message;
            }
            return View("~/Views/Oferta/ConsultarOferta.cshtml", oferta.AsEnumerable());
        }


        public ActionResult AplicarOferta(int idOferta, int idSolicitante)
        {
            string resultado = "";
            try
            {
                resultado = ofertaDALServicio.aplicarOfertaId(idOferta.ToString(), idSolicitante.ToString());
                ViewBag.Message = resultado;// "Ha aplicado a la oferta correctamente.";
            }
            catch(Exception ex)
            {
                ViewBag.Message = "Hubo un error al aplicar a la oferta. " + ex.Message;
            }
            return View("~/Views/Oferta/oferta.cshtml");
        }

        #endregion Experimento




    }
}

PruebaMvc/Views/Oferta/ConsultarOferta.cshtml
@model IEnumerable<PruebaMvc.ModelsService.OfertaS>
@{
    ViewBag.Title = "Consultar oferta";
}
@using (Html.BeginForm("ConsultarTodasOferta", "Oferta", FormMethod.Post))
{
<br />
<div class="panel panel-default">
    <div class="panel-heading"><h4>Consultar Oferta</h4></div>
    <div class="panel-body">
        <table>
            <tr>
                <td>
                    Filtro
                </td>
                <td>
                    <select id="tipoControl" name="tipoControl">
                        <option value="1">Oferente</option>
                        <option value="2">Todas</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Valor
                </td>
                <td>
                    <input type="text" id="idValor" name="valor">
                </td>
                <td colspan="2" align="left">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h4>Ofertas</h4></div>
    <div class="panel-body">

        @if (Model != null)
        {
            <table class="table table-striped">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fechaInicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fechaFin)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.descripcion)
                    </th>
                    <th>
                        Opciones
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.fechaInicio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.fechaFin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.descripcion)
                        </td>
                        <td>
                            @Html.ActionLink("Ver", "ConsultarOfertaId", new { idOferta = item.id }, "btn btn - danger")
                        </td>
                    </tr>
                }

            </table>
        }
    </div>
</div>
}

PruebaMvc/Views/Oferta/Oferta.cshtml
@model PruebaMvc.ModelsService.OfertaS
@{

}

@using (Html.BeginForm("AplicarOferta", "Oferta", FormMethod.Post))
{
<div class="panel-heading">
    <h3>Detalle de oferta</h3>
    <h5>Información básica de oferta</h5>
</div>
<div class="panel-body">

    @if (Model != null)
    {
        <table class="table table-striped">
            <tr>
                <td>
                    <input type="hidden" value="@Model.id" name="idOferta" />
                    @Html.HiddenFor(model => model.nombre)
                    Nombre: @Html.DisplayFor(model => model.nombre)
                </td>
                <td>
                    @Html.HiddenFor(model => model.tipoOferta)
                    Tipo oferta: @Html.DisplayFor(model => model.tipoOferta)
                </td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>
                    @Html.HiddenFor(model => model.fechaInicio)
                    Fecha inicio: @Html.DisplayFor(model => model.fechaInicio)
                </td>
                <td>
                    @Html.HiddenFor(model => model.fechaFin)
                    Fecha inicio: @Html.DisplayFor(model => model.fechaFin)
                </td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td colspan="4">
                    Descripción:
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    @Html.HiddenFor(model => model.descripcion)
                    @Html.DisplayFor(model => model.descripcion)
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    Requisitos:
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    @Html.HiddenFor(model => model.requisitos)
                    @Html.DisplayFor(model => model.requisitos)
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    Condiciones:
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    @Html.HiddenFor(model => model.condiciones)
                    @Html.DisplayFor(model => model.condiciones)
                </td>
            </tr>
        </table>
    }
</div>
<div class="panel-footer" style="text-align:right">
    <input type="hidden" value="1" name="idSolicitante" />
    <button type="submit" class="btn btn-success" >Aplicar a oferta</button>
</div>
<br />
<h1 class="label label-success">@ViewBag.Message</h1>
}