PruebaMvc/Controllers/GestionarFormularioController.cs
using PruebaMvc.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;


namespace PruebaMvc.Controllers
{
    public class GestionarFormularioController : Controller
    {
        private String cedula = "1023";
        private int MULTI_SELECCION = 7;
        private int DOCUMENTO_ADJUNTO = 8;

        String connString = ConfigurationManager.ConnectionStrings["PortalBecas"].ConnectionString;

        // GET: Home
        [Authorize(Roles = "Administrador,Solicitante")]
        public ActionResult Formulario()
        {
            Items lista = new Items(cedula);

            try
            {
                SqlConnection conn = new SqlConnection(connString);
                conn.Open();
                SqlCommand testCMD = new SqlCommand("spCrearFormularioSolicitante", conn);
                testCMD.CommandType = CommandType.StoredProcedure;

                testCMD.Parameters.Add("@Cedula", SqlDbType.VarChar, 20).Value = cedula;
                testCMD.ExecuteNonQuery();

                conn.Close();
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Hubo un error al gestionar el formulario" + ex.Message;
            }

            return View(lista);
        }

        [Authorize(Roles = "Administrador,Solicitante")]
        public ActionResult Guardar(Items items, HttpPostedFileBase file)
        {

            //Documento adjunto

            try
            {
                SqlConnection conn = new SqlConnection(connString);
                conn.Open();
                SqlCommand testCMD = new SqlCommand("spCalificarItems", conn);
                testCMD.CommandType = CommandType.StoredProcedure;

                string path = "";

                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string fileName = Path.GetFileName(file.FileName);
                        path = Path.Combine(Server.MapPath("~/Documents"), fileName);
                        file.SaveAs(path);
                    }
                }

                foreach (Item item in items.lstItems)
                {

                    if (item.IdTipoControl == MULTI_SELECCION)
                        item.valor = obtenerSeleccionMultiple(item);

                    if (item.IdTipoControl == DOCUMENTO_ADJUNTO)
                        item.valor = path;

                    testCMD.Parameters.Clear();
                    testCMD.Parameters.Add("@Cedula", SqlDbType.VarChar, 20).Value = item.Cedula;
                    testCMD.Parameters.Add("@IdItem", SqlDbType.Int).Value = item.Id;
                    testCMD.Parameters.Add("@Valor", SqlDbType.VarChar, 100).Value = item.valor == null? "" : item.valor;
                    testCMD.ExecuteNonQuery();
                }

                conn.Close();
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Hubo un error al gestionar el formulario" + ex.Message;
            }

            return View();
        }

        private String obtenerSeleccionMultiple(Item item)
        {
            String valor = "";
            foreach (Respuesta respuesta in item.lstRespuestas)
            {
                valor = respuesta.seleccion ? valor + "," + respuesta.respuesta : valor;
            }

            return valor.TrimStart(',');
        }

    }
}

PruebaMvc/Views/GestionarFormulario/Formulario.cshtml
@model PruebaMvc.Models.Items
@{
    ViewBag.Title = "Gestionar Formulario";
}

@using (Html.BeginForm("Guardar", "GestionarFormulario", FormMethod.Post, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Gestionar Formulario</div>
        <div class="panel-body">
            <table>
                @for (int i = 0; i < Model.lstItems.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(model => model.lstItems[i].Cedula)
                            @Html.HiddenFor(model => model.lstItems[i].Id)
                            @Html.HiddenFor(model => model.lstItems[i].IdTipoControl)
                            @Html.LabelFor(model => model.lstItems[i].Descripcion, Model.lstItems[i].Descripcion)
                        </td>
                        <td>
                            @switch (Model.lstItems[i].IdTipoControl)
                            {
                                case 4:
                                    @Html.EditorFor(model => model.lstItems[i].valor)
                                    break;
                                case 5:
                                    @Html.DropDownListFor(model => model.lstItems[i].valor, new SelectList(Model.lstItems[i].lstRespuestas.Select(l => l.respuesta)), "Seleccione", new { @class = "form-control" })
                                    break;
                                case 6:
                                    for (int j = 0; j < Model.lstItems[i].lstRespuestas.Count; j++)
                                    {
                                        @Html.RadioButtonFor(model => model.lstItems[i].valor, Model.lstItems[i].lstRespuestas[j].respuesta);
                                        @Html.Label(Model.lstItems[i].lstRespuestas[j].respuesta)
                                    }
                                    break;
                                case 7:
                                    for (int j = 0; j < Model.lstItems[i].lstRespuestas.Count; j++)
                                    {
                                        <table>
                                            <tr>
                                                <td>
                                                    @Html.HiddenFor(model => model.lstItems[i].lstRespuestas[j].respuesta)
                                                    @Html.CheckBoxFor(model => Model.lstItems[i].lstRespuestas[j].seleccion)
                                                    @Html.Label(Model.lstItems[i].lstRespuestas[j].respuesta)
                                                </td>
                                            </tr>
                                        </table>
                                    }
                                    break;
                                case 8:
                                    @Html.TextBox("file", "", new { type = "file" })
                                    break;
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

    <button type="submit" class="btn btn-success">Guardar</button>
}

PruebaMvc/Views/GestionarFormulario/Guardar.cshtml
@{
    ViewBag.Title = "Guardar";
}

<h2>Guardar</h2>