PruebaMvc/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace PruebaMvc.Models
{
	public class Usuario
	{
		public int IdUsuario { get; set; }
		[Required(ErrorMessage = "El nombre de usuario es requerido")]
		[Display(Name ="Nombre Usuario")]
        public String NombreUsuario { get; set; }
        public String CorreoElectronico { get; set; }
		[Required(ErrorMessage =  "La clave es requerida")]
		[Display(Name = "Contraseña")]
		public String Clave { get; set; }
        public String ConfirmarClave { get; set; }
        public String Rol { get; set; }
    }
}

PruebaMvc/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaMvc.Controllers
{
    public class InicioController : Controller
    {
        // GET: Inicio
        [Authorize]
        public ActionResult Inicio()
        {
            return View();
        }

        public ActionResult CrearFormularioDinamico()
        {
            return View();
        }

        public ActionResult CrearUsuarios()
        {
            return View();
        }
    }
}

PruebaMvc/Controllers/UsuarioController.cs
using PruebaMvc.DAL;
using PruebaMvc.Models;
using PruebaMvc.ModelsService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaMvc.Controllers
{
    public class UsuarioController : Controller
    {
        OfertaDALServicio ofertaDALServicio = new OfertaDALServicio();

		public UsuarioController()
		{
			ViewBag.ConsultaRealizada = false;
		}

        // GET: Usuario
        public ActionResult CrearOferente()
        {
            List<SelectListItem> Pais = new List<SelectListItem>();
            Pais.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            Pais.Add(new SelectListItem() { Text = "Colombia", Value = "1" });
            Pais.Add(new SelectListItem() { Text = "Perú", Value = "2" });

            ViewBag.Pais = new SelectList(Pais, "Value", "Text");

            List<SelectListItem> TipoOferente = new List<SelectListItem>();
            TipoOferente.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            TipoOferente.Add(new SelectListItem() { Text = "Fundación", Value = "1" });
            TipoOferente.Add(new SelectListItem() { Text = "Organización", Value = "2" });

            ViewBag.TipoOferente = new SelectList(TipoOferente, "Value", "Text");

            OferenteCrear oferente = new OferenteCrear();
            return View("~/Views/Usuario/CrearOferente.cshtml", oferente);
        }

        public ActionResult GuardarOferente(OferenteCrear oferente)
        {
            string resultado = "";
            OferenteConsulta oferenteNuevo = new OferenteConsulta();
            oferenteNuevo = ofertaDALServicio.crearOferente(oferente);
            ViewBag.Message = "El oferente fue creado correctamente";
            return View("~/Views/Usuario/ConsultarOferente.cshtml", oferenteNuevo);
        }

        public ActionResult CrearSolicitante()
        {
            List<SelectListItem> TipoDocumento = new List<SelectListItem>();
            TipoDocumento.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            TipoDocumento.Add(new SelectListItem() { Text = "Cedula", Value = "1" });
            TipoDocumento.Add(new SelectListItem() { Text = "Tarjeta de identidad", Value = "2" });

            ViewBag.TipoDocumento = new SelectList(TipoDocumento, "Value", "Text");

            List<SelectListItem> Sexo = new List<SelectListItem>();
            Sexo.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            Sexo.Add(new SelectListItem() { Text = "Masculino", Value = "1" });
            Sexo.Add(new SelectListItem() { Text = "Femenino", Value = "2" });

            ViewBag.Sexo = new SelectList(Sexo, "Value", "Text");

            List<SelectListItem> TipoPoblacion = new List<SelectListItem>();
            TipoPoblacion.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            TipoPoblacion.Add(new SelectListItem() { Text = "Desplazados", Value = "1" });
            TipoPoblacion.Add(new SelectListItem() { Text = "Vulnerables", Value = "2" });

            ViewBag.TipoPoblacion = new SelectList(TipoPoblacion, "Value", "Text");

            List<SelectListItem> Pais = new List<SelectListItem>();
            Pais.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            Pais.Add(new SelectListItem() { Text = "Colombia", Value = "1" });
            Pais.Add(new SelectListItem() { Text = "Perú", Value = "2" });

            ViewBag.Pais = new SelectList(Pais, "Value", "Text");

            List<SelectListItem> Departamento = new List<SelectListItem>();
            Departamento.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            Departamento.Add(new SelectListItem() { Text = "Cundinamarca", Value = "1" });
            Departamento.Add(new SelectListItem() { Text = "Santander", Value = "2" });

            ViewBag.Departamento = new SelectList(Departamento, "Value", "Text");

            List<SelectListItem> Ciudad = new List<SelectListItem>();
            Ciudad.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            Ciudad.Add(new SelectListItem() { Text = "Bogotá", Value = "1" });
            Ciudad.Add(new SelectListItem() { Text = "Bucaramanga", Value = "2" });

            ViewBag.Ciudad = new SelectList(Ciudad, "Value", "Text");

            SolicitanteCrear solicitante = new SolicitanteCrear();
            return View("~/Views/Usuario/CrearSolicitante.cshtml", solicitante);
        }

        public ActionResult GuardarSolicitante(SolicitanteCrear solicitante)
        {
            string resultado = "";
            SolicitanteConsulta solicitanteNuevo = new SolicitanteConsulta();
            solicitanteNuevo = ofertaDALServicio.crearSolicitante(solicitante);
            ViewBag.Message = "El solicitante fue creado correctamente";
            return View("~/Views/Usuario/ConsultarSolicitante.cshtml", solicitanteNuevo);
        }

        public ActionResult EliminarSolicitante()
        {
            Solicitante solicitante = new Solicitante();
            return View(solicitante);
        }

        public ActionResult BorrarSolicitante(Solicitante solicitante)
        {
            return View("~/Views/Usuario/CrearSolicitante.cshtml", solicitante);
        }

        public ActionResult consultarOferente()
        {
            OferenteConsulta oferente = new OferenteConsulta();
            return View("~/Views/Usuario/ConsultarOferente.cshtml", oferente);
        }

		[HttpGet]
		public ActionResult consultarOferenteId()
		{
			return View("ConsultarOferente");
		}

		[HttpPost]
        public ActionResult consultarOferenteId(String idOferente)
        {

            OferenteConsulta oferente = new OferenteConsulta();
            try
            {
                oferente = ofertaDALServicio.obtenerOferente(idOferente);
				ViewBag.ConsultaRealizada = true;
			}
            catch (Exception ex)
            {
                ViewBag.Message = "Hubo un error al aplicar a la oferta. " + ex.Message;
            }



            return View("~/Views/Usuario/ConsultarOferente.cshtml", oferente);
        }



        public ActionResult consultarSolicitante()
        {
            SolicitanteConsulta solicitante = new SolicitanteConsulta();
            return View("~/Views/Usuario/ConsultarSolicitante.cshtml", solicitante);
        }

		[HttpGet]
		public ActionResult consultarSolicitanteId()
		{
			return View("ConsultarSolicitante");
		}

		[HttpPost]
		public ActionResult consultarSolicitanteId(String idSolicitante)
        {
            SolicitanteConsulta solicitante = new SolicitanteConsulta();

            try
            {
                solicitante = ofertaDALServicio.obtenerSolicitante(idSolicitante);
				ViewBag.ConsultaRealizada = true;
			}
            catch (Exception ex)
            {
                ViewBag.Message = "Hubo un error al aplicar a la oferta. " + ex.Message;
            }
            return View("~/Views/Usuario/ConsultarSolicitante.cshtml", solicitante);
        }
    }
}

PruebaMvc/Views/Usuario/ConsultarOferente.cshtml
@model PruebaMvc.ModelsService.OferenteConsulta
@{

}
<br />
@using (Html.BeginForm("consultarOferenteId", "Usuario", FormMethod.Post))
{
	<div class="panel panel-default">
		<div class="panel-heading"><h4>Consultar Oferente</h4></div>
		<div class="panel-body">
			<div class="container">
				<div class="form-group">
					<label class="col-sm-2">Id Oferente</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" id="id_Oferente" name="idOferente">
					</div>

					<button type="submit" class="col-sm-1 btn btn-success">Buscar</button>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="form-group">
			<a class="btn btn-primary" href="@Url.Action("CrearUsuarios", "Inicio")">Atrás</a>
		</div>

	</div>



	if ((bool)ViewBag.ConsultaRealizada)
	{
		if (Model != null)
		{
			<div class="panel-heading">
				<h3>Datos Oferente</h3>
			</div>
			<div class="panel-body">
				<h2 class="label label-success">@ViewBag.Message</h2>

				<table class="table table-striped">
					<tr>
						<td class="width-columnKey">
							<strong>Nombre</strong>
						</td>
						<td class="width-columnValue">
							@Html.HiddenFor(model => model.nombre)
							@Html.DisplayFor(model => model.nombre)
						</td>
					</tr>
					<tr>
						<td>
							<strong>Correo Electrónico</strong>
						</td>
						<td>
							@Html.HiddenFor(model => model.correoElectronico)
							@Html.DisplayFor(model => model.correoElectronico)
						</td>
					</tr>
					<tr>
						<td>
							<strong>Tipo Usuario</strong>
						</td>
						<td>
							@Html.HiddenFor(model => model.rol.nombre)
							@Html.DisplayFor(model => model.rol.nombre)
						</td>
					</tr>
					<tr>
						<td>
							<strong>Estado</strong>
						</td>
						<td>
							@Html.HiddenFor(model => model.idEstadoSistema.descripcion)
							@Html.DisplayFor(model => model.idEstadoSistema.descripcion)
						</td>
					</tr>
					<tr>
						<td>
							<strong>Nit</strong>
						</td>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.nit)
							@Html.DisplayFor(model => model.infoUsuario.nit)
						</td>
					</tr>
					<tr>
						<td>
							<strong>Descripción</strong>
						</td>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.descripcion)
							@Html.DisplayFor(model => model.infoUsuario.descripcion)
						</td>
					</tr>
					<tr>
						<td>
							<strong>Tipo entidad</strong>
						</td>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.tipoEntidad.nombre)
							@Html.DisplayFor(model => model.infoUsuario.tipoEntidad.nombre)
						</td>
					</tr>
					<tr>
						<td>
							<strong>Pais</strong>
						</td>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.pais.nombre)
							@Html.DisplayFor(model => model.infoUsuario.pais.nombre)
						</td>
					</tr>

				</table>

			</div>

		}
		else
		{
			<p>No se encontraron resultados asociados a la consulta</p>
		}

	}


}

PruebaMvc/Views/Usuario/ConsultarSolicitante.cshtml
@model PruebaMvc.ModelsService.SolicitanteConsulta
@{

}

@using (Html.BeginForm("consultarSolicitanteId", "Usuario", FormMethod.Post))
{

	<div class="panel panel-default">
		<div class="panel-heading"><h4>Consultar Solicitante</h4></div>
		<div class="panel-body">
			<div class="container">
				<div class="form-group">
					<label class="col-sm-2">Id Solicitante</label>
					<div class="col-sm-3">
						<input class="form-control" type="text" id="id_Oferente" name="idSolicitante">
					</div>
					<button type="submit" class="col-sm-1 btn btn-success">Buscar</button>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="form-group">
			<a class="btn btn-primary" href="@Url.Action("CrearUsuarios", "Inicio")">Atrás</a>
		</div>

	</div>

	@*<div class="panel panel-default">
			<div class="panel-heading"><h4>Consultar Solicitante</h4></div>
			<div class="panel-body">
				<table>
					<tr>
						<td>
							Id Solicitante
						</td>
						<td>
							<input type="text" id="id_Oferente" name="idSolicitante">
						</td>
						<td colspan="2" align="left">
							<button type="submit" class="btn btn-primary">Buscar</button>
						</td>
					</tr>
				</table>
			</div>
		</div>*@

if ((bool)ViewBag.ConsultaRealizada)
{
	if (Model != null)
	{
		<div class="panel-heading">
			<h3>Consulta Solicitante</h3>
		</div>
		<div class="panel-body">
			<table class="table table-striped">
				<tr>
					<td>
						<strong>Nombres</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.nombre)
						@Html.DisplayFor(model => model.nombre)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Apellidos</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.infoUsuario.apellidos)
						@Html.DisplayFor(model => model.infoUsuario.apellidos)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Correo Electrónico</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.correoElectronico)
						@Html.DisplayFor(model => model.correoElectronico)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Tipo Usuario</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.rol.nombre)
						@Html.DisplayFor(model => model.rol.nombre)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Estado</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.idEstadoSistema.descripcion)
						@Html.DisplayFor(model => model.idEstadoSistema.descripcion)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Tipo de documento</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.infoUsuario.id_tipo_documento.descripcion)
						@Html.DisplayFor(model => model.infoUsuario.id_tipo_documento.descripcion)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Número Documento</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.infoUsuario.numero_documento)
						@Html.DisplayFor(model => model.infoUsuario.numero_documento)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Género</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.infoUsuario.sexo.descripcion)
						@Html.DisplayFor(model => model.infoUsuario.sexo.descripcion)
					</td>
				</tr>
				<tr>
					<td>
						<strong>Pais de Nacimiento</strong>
					</td>
					<td>
						@Html.HiddenFor(model => model.infoUsuario.pais_nacimiento.nombre)
						@Html.DisplayFor(model => model.infoUsuario.pais_nacimiento.nombre)
					</td>
				</tr>
			</table>

		</div>
	}
	else
	{
		<p>No se encontraron resultados asociados a la consulta </p>
	}

	@*<div class="panel-heading">
			<h3>Consulta Solicitante</h3>
		</div>
		<div class="panel-body">

			@if (Model != null)
			{
				<table class="table table-striped">
					<tr>
						<td>
							@Html.HiddenFor(model => model.nombre)
							Nombre: @Html.DisplayFor(model => model.nombre)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.apellidos)
							Apellidos: @Html.DisplayFor(model => model.infoUsuario.apellidos)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.correoElectronico)
							Correo electrónico: @Html.DisplayFor(model => model.correoElectronico)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.rol.nombre)
							Tipo Usuario: @Html.DisplayFor(model => model.rol.nombre)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.idEstadoSistema.descripcion)
							Estado: @Html.DisplayFor(model => model.idEstadoSistema.descripcion)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.id_tipo_documento.descripcion)
							Tipo de documento: @Html.DisplayFor(model => model.infoUsuario.id_tipo_documento.descripcion)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.numero_documento)
							Número documento: @Html.DisplayFor(model => model.infoUsuario.numero_documento)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.sexo.descripcion)
							Sexo: @Html.DisplayFor(model => model.infoUsuario.sexo.descripcion)
						</td>
					</tr>
					<tr>
						<td>
							@Html.HiddenFor(model => model.infoUsuario.pais_nacimiento.nombre)
							Pais de nacimiento: @Html.DisplayFor(model => model.infoUsuario.pais_nacimiento.nombre)
						</td>
					</tr>
				</table>
			}
		</div>*@
	}
}

PruebaMvc/Views/Usuario/CrearAdministrador.cshtml
@model PruebaMvc.Models.Administrador

@{
    SelectList lstSede = ViewBag.Sede;
}

@using (Html.BeginForm("GuardarAdministrador", "Usuario", FormMethod.Post))
{
    <br />
    <div class="panel panel-default">
        <div class="panel-heading"><h4>Creación de cuenta: administrador</h4></div>
        <div class="panel-body">
            <table>
                <tr>
                    <td colspan="2">
                        <h4>Datos de usuario</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        Usuario: @Html.EditorFor(model => model.NombreUsuario)
                    </td>
                    <td>
                        Correo electrónico: @Html.EditorFor(model => model.CorreoElectronico)
                    </td>
                </tr>
                <tr>
                    <td>
                        Contraseña: @Html.EditorFor(model => model.Clave)
                    </td>
                    <td>
                        Confirmar contraseña: @Html.EditorFor(model => model.ConfirmarClave)
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <h4>Datos de funcionario</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        Nombres: @Html.EditorFor(model => model.Nombres)
                    </td>
                    <td>
                        Apellidos: @Html.EditorFor(model => model.Apellidos)
                    </td>
                </tr>
                <tr>
                    <td>
                        Cargo: @Html.EditorFor(model => model.Cargo)
                    </td>
                </tr>
                <tr>
                    <td>
                        Sede
                        @Html.DropDownListFor(model => model.IdSede, ViewBag.Sede as IEnumerable<SelectListItem>, new { @class = "form-control" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <br />
                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" class="btn btn-success">Crear</button>
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

PruebaMvc/Views/Usuario/CrearOferente.cshtml
@model PruebaMvc.ModelsService.OferenteCrear
@using PruebaMvc.UtilidadesUI

@{
	SelectList lstPais = ViewBag.Pais;
	SelectList lstTipoOferente = ViewBag.TipoOferente;
	ViewBag.Title = "Crear Oferente";
}

@using (Html.BeginForm("GuardarOferente", "Usuario", FormMethod.Post))
{
	<br />
	<div class="panel panel-default">
		<div class="panel-heading"><h4>Creación de cuenta: Oferente</h4></div>
		<div class="container">
			<h4>Datos de Usuario</h4>
			<div class="row top-buffer">
				@*First Row*@
				<div class="form-group">
					@*<label class="col-sm-2">Usuario</label>*@
					@Html.RequiredLabelFor(model => model.nombreUsuario, new { @class= "col-sm-2" })
					<div class="col-sm-4 input-append">
						@Html.EditorFor(model => model.nombreUsuario, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.nombreUsuario, "", new { @class = "text-danger" })
					</div>
					@*<label class="col-sm-2">Correo Electrónico:</label>*@
					@Html.RequiredLabelFor(model => model.correoElectronico, new { @class = "col-sm-2" })
					<div class="col-sm-4">
						@*@Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })*@
						@Html.EditorFor(model => model.correoElectronico, new { htmlAttributes = new { @class = "form-control", placeholder ="correo@dominio.com" } })
						@Html.ValidationMessageFor(model => model.correoElectronico, "", new { @class = "text-danger" })
					</div>
				</div>
			</div>

			@*Second Row*@
			<div class="row top-buffer">
				<div class="form-group">
					@*<label class="col-sm-2">Contraseña:</label>*@
					@Html.RequiredLabelFor(model => model.contrasena, new { @class = "col-sm-2" })
					<div class="col-sm-4">
						@*@Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })*@
						@Html.PasswordFor(model => model.contrasena, new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.contrasena, "", new { @class = "text-danger" })
					</div>
					@*<label class="col-sm-2">Confirmar contraseña:</label>*@
					@Html.RequiredLabelFor(model => model.confirmarContrasena, new { @class = "col-sm-2" })
					<div class="col-sm-4">
						@*@Html.EditorFor(model => model.ConfirmarClave, new { htmlAttributes = new { @class = "form-control" } })*@
						@Html.PasswordFor(model => model.confirmarContrasena, new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.confirmarContrasena, "", new { @class = "text-danger" })
					</div>
				</div>
			</div>

			<hr />
		</div>

		<div class="container">
			<h4>Datos de Oferente</h4>

			<div class="row top-buffer">
				@*First Row*@
				<div class="form-group">
					@Html.RequiredLabelFor(model => model.nit, new { @class = "col-sm-2" })
					@*<label class="col-sm-2">Nit:</label>*@
					<div class="col-sm-4 input-append">
						@Html.EditorFor(model => model.nit, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.nit, "", new { @class = "text-danger" })
					</div>
					@*<label class="col-sm-2">Nombre:</label>*@
					@Html.RequiredLabelFor(model => model.nombre, new { @class = "col-sm-2" })
					<div class="col-sm-4">
						@Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
					</div>
				</div>
			</div>			

			<div class="row top-buffer">
				@*Second Row*@
				<div class="form-group">
					@*<label class="col-sm-2">País:</label>*@
					@Html.RequiredLabelFor(model => model.pais, new { @class = "col-sm-2" })
					<div class="col-sm-4 input-append">
						@Html.DropDownListFor(model => model.pais, ViewBag.Pais as IEnumerable<SelectListItem>, new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.pais, "", new { @class = "text-danger" })
					</div>

					@*<label class="col-sm-2">Tipo de entidad:</label>*@
					@Html.RequiredLabelFor(model => model.tipoEntidad, new { @class = "col-sm-2" })
					<div class="col-sm-4">
						@Html.DropDownListFor(model => model.tipoEntidad, ViewBag.TipoOferente as IEnumerable<SelectListItem>, new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.tipoEntidad, "", new { @class = "text-danger" })
					</div>
				</div>
			</div>

		</div>

		<div class="container">
			<div class="row top-buffer">
				@*Second Row*@
				<div class="form-group">					
					<label class="col-sm-2">Descripción:</label>
					<div class="col-sm-10">
						@Html.TextAreaFor(model => model.descripcion, 15, 100, new { @class = "form-control width-textarea" })
					</div>
				</div>
			</div>

		</div>		

		<div class="container">
			<div class="form-group btn-container">
				<button type="submit" class="btn btn-success">Crear Oferente</button>
				<a class="btn btn-primary" href="@Url.Action("CrearUsuarios", "Inicio")">Cancelar</a>
			</div>
		</div>	


	</div>

	@*<div class="panel-body">





		<table>
			<tr>
				<td colspan="2">
					<h4>Datos de usuario</h4>
				</td>
			</tr>
			<tr>
				<td>
					Usuario: @Html.EditorFor(model => model.NombreUsuario, new { @required = true })
				</td>
				<td>
					Correo electrónico: @Html.EditorFor(model => model.CorreoElectronico)
				</td>
			</tr>
			<tr>
				<td>
					Contraseña: @Html.EditorFor(model => model.Clave)
				</td>
				<td>
					Confirmar contraseña: @Html.EditorFor(model => model.ConfirmarClave)
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<h4>Datos de oferente</h4>
				</td>
			</tr>
			<tr>
				<td>
					Nit: @Html.EditorFor(model => model.nit)
				</td>
				<td>
					Nombre: @Html.EditorFor(model => model.nombre)
				</td>
			</tr>
			<tr>
				<td>
					País:
					@Html.DropDownListFor(model => model.id_pais, ViewBag.Pais as IEnumerable<SelectListItem>, new { @class = "form-control" })
				</td>
			</tr>
			<tr>
				<td>
					Tipo de entidad
					@Html.DropDownListFor(model => model.id_tipo_entidad, ViewBag.TipoOferente as IEnumerable<SelectListItem>, new { @class = "form-control" })
				</td>
			</tr>
			<tr>
				<td>
					Descripción
					@Html.TextAreaFor(model => model.descripcion, 15, 8, new { @class = "form-control" })
				</td>
			</tr>
			<tr>
				<td>
					<button type="submit" class="btn btn-success">Crear oferente</button>
				</td>
			</tr>
		</table>
	</div>*@

}