PruebaMvc/Controllers/CrearFormularioController.cs
using PruebaMvc.DAL;
using PruebaMvc.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace PruebaMvc.Controllers
{
    public class CrearFormularioController : Controller
    {
        private String cedula = "1023";
        FormularioDAL formularioDAL = new FormularioDAL();
        String connString = ConfigurationManager.ConnectionStrings["PortalBecas"].ConnectionString;

        [Authorize(Roles = "Administrador,Oferente")]
        public ActionResult CrearFormulario()
        {
            Items lista = new Items(cedula);

            return View(lista);
        }

        [Authorize(Roles = "Administrador,Oferente")]
        [MultipleButton(Name = "action", Argument = "AgregarItem")]
        public ActionResult AgregarItem(String cedula, String nombreItem, String tipoControl, String tipoDelimitador, String opciones, Items items)
        {
            Items listaItems = new Items();
            try
            {
                Item item = new Item();
                item.Descripcion = nombreItem;
                item.IdTipoControl = Convert.ToInt16(tipoControl);
                if (opciones.Trim() != "")
                {
                    List<Respuesta> listaRespuestas = new List<Respuesta>();
                    String[] respuestas = opciones.Split(Convert.ToChar(tipoDelimitador));

                    foreach (String respuesta in respuestas)
                    {
                        Respuesta respuestaItem = new Respuesta { respuesta = respuesta };
                        listaRespuestas.Add(respuestaItem);
                    }

                    item.lstRespuestas = listaRespuestas;
                }

                List<Item> lista = new List<Item>();
                if (items.lstItems != null)
                {
                    lista = items.lstItems;
                }
                lista.Add(item);
                listaItems.lstItems = lista;
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Hubo un error al gestionar el formulario" + ex.Message;
            }

            return View("~/Views/CrearFormulario/CrearFormulario.cshtml", listaItems);
        }

        [Authorize(Roles = "Administrador,Oferente")]
        [MultipleButton(Name = "action", Argument = "GuardarFormulario")]
        public ActionResult GuardarFormulario(String cedula, Items items)
        {
            try
            {
                formularioDAL.crearFormulario(cedula, items);
                ViewBag.Message = "El formulario fue creado correctamente";
            }
            catch(Exception ex)
            {
                ViewBag.Message = "Hubo un error al crear el formulario. " + ex.Message;
            }

            return View("~/Views/CrearFormulario/CrearFormulario.cshtml");
        }

        [Authorize(Roles = "Administrador,Oferente")]
        [MultipleButton(Name = "action", Argument = "BorrarFormulario")]
        public ActionResult BorrarFormulario(Items items)
        {
            try
            {
                formularioDAL.borrarFormulario(cedula);
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Hubo un error al gestionar el formulario" + ex.Message;
            }

            return View("~/Views/CrearFormulario/CrearFormulario.cshtml");
        }
    }

}

[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public class MultipleButtonAttribute : ActionNameSelectorAttribute
{
    public string Name { get; set; }
    public string Argument { get; set; }

    public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo)
    {
        var isValidName = false;
        var keyValue = string.Format("{0}:{1}", Name, Argument);
        var value = controllerContext.Controller.ValueProvider.GetValue(keyValue);

        if (value != null)
        {
            controllerContext.Controller.ControllerContext.RouteData.Values[Name] = Argument;
            isValidName = true;
        }

        return isValidName;
    }
}

PruebaMvc/Views/CrearFormulario/CrearFormulario.cshtml
@model PruebaMvc.Models.Items
@{
    ViewBag.Title = "Crear Formulario";
}

<br />
<h2 class="label label-success">@ViewBag.Message</h2>

@using (Html.BeginForm("AgregarItem", "CrearFormulario", FormMethod.Post))
{ 
    <div class="panel panel-default">
        <div class="panel-heading">Crear formulario</div>
        <div class="panel-body">
            <table>
                <tr>
                    <td>
                        <input type="hidden" name="cedula" value="1023" />
                        Ingrese el item
                    </td>
                    <td>
                        <input type="text" id="nombreItemId" name="nombreItem">
                    </td>
                </tr>
                <tr>
                    <td>
                        Tipo de respuesta
                    </td>
                    <td>
                        <select id="tipoControl" name="tipoControl">
                            <option value="1">Titulo</option>
                            <option value="2">Descripción</option>
                            <option value="3">Comentario</option>
                            <option value="4">Caja de texto</option>
                            <option value="5">Lista desplegable</option>
                            <option value="6">Botón de radio</option>
                            <option value="7">Selección múltiple</option>
                            <option value="8">Documento adjunto</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        Las opciones se delimitan con :
                    </td>
                    <td>
                        <input type="text" id="tipoDelimitadorId" name="tipoDelimitador">
                    </td>
                </tr>
                <tr>
                    <td>
                        Opciones
                    </td>
                    <td>
                        <input type="text" id="opcionesId" name="opciones">
                    </td>
                </tr>
                <tr>
                    <td>
                        <br />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="left">
                        <button type="submit" class="btn btn-primary" name="action:AgregarItem">Guardar Item</button>
                    </td>
                </tr>
                <tr>
                    <td>
                        <br />
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Vista Previa</div>
        <div class="panel-body">

            @if (Model != null)
            {
                <table>
                    <tr>
                        <td>
                            <br />
                        </td>
                    </tr>
                    @for (int i = 0; i < Model.lstItems.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.HiddenFor(model => model.lstItems[i].Cedula)
                                @Html.HiddenFor(model => model.lstItems[i].IdTipoControl)
                                @Html.HiddenFor(model => model.lstItems[i].Descripcion)
                            </td>
                        </tr>
                        <tr>
                            @if (Model.lstItems[i].IdTipoControl < 4)
                            {
                                <td colspan="2">
                                    @Html.LabelFor(model => model.lstItems[i].Descripcion, Model.lstItems[i].Descripcion)
                                </td>
                            }
                            else
                            {
                                <td>
                                    @Html.LabelFor(model => model.lstItems[i].Descripcion, Model.lstItems[i].Descripcion)
                                </td>
                                <td>
                                    @switch (Model.lstItems[i].IdTipoControl)
                                    {
                                        case 4:
                                            @Html.EditorFor(model => model.lstItems[i].valor, new { htmlAttributes = new { @class = "form-control" } })
                                            break;
                                        case 5:
                                            for (int j = 0; j < Model.lstItems[i].lstRespuestas.Count; j++)
                                            {
                                                @Html.HiddenFor(model => model.lstItems[i].lstRespuestas[j].respuesta)
                                            }
                                            @Html.DropDownListFor(model => model.lstItems[i].valor, new SelectList(Model.lstItems[i].lstRespuestas.Select(l => l.respuesta)), "Seleccione", new { @class = "form-control" })
                                            break;
                                        case 6:
                                            for (int j = 0; j < Model.lstItems[i].lstRespuestas.Count; j++)
                                            {
                                                @Html.HiddenFor(model => model.lstItems[i].lstRespuestas[j].respuesta)
                                                @Html.RadioButtonFor(model => model.lstItems[i].valor, Model.lstItems[i].lstRespuestas[j].respuesta);
                                                @Html.Label(Model.lstItems[i].lstRespuestas[j].respuesta)
                                            }
                                            break;
                                        case 7:
                                            for (int j = 0; j < Model.lstItems[i].lstRespuestas.Count; j++)
                                            {
                                                <table>
                                                    <tr>
                                                        <td>
                                                            @Html.HiddenFor(model => model.lstItems[i].lstRespuestas[j].respuesta)
                                                            @Html.CheckBoxFor(model => Model.lstItems[i].lstRespuestas[j].seleccion)
                                                            @Html.Label(Model.lstItems[i].lstRespuestas[j].respuesta)
                                                        </td>
                                                    </tr>
                                                </table>
                                            }
                                            break;
                                        case 8:
                                            @Html.TextBox("file", "", new { type = "file" })
                                            break;
                                    }
                                </td>
                            }
                           @*<td width="5%">
                                <input type="hidden" value="@Model.lstItems[i].Descripcion" name="descripcion" id="@i.ToString()" />
                                <input type="submit" value="@Model.lstItems[i].Descripcion" name="action:BorrarItem" />

                                @Html.ActionLink("Borrar", "BorrarItem", new { IdTipoControl = Model.lstItems[i].IdTipoControl},"btn btn - danger"
                            </td>*@

                        </tr>
                    }
                    <tr>
                        <td>
                            <br />
                            <br />
                        </td>
                    </tr>
                </table>
            }

        </div>
    </div>

    <button type="submit" class="btn btn-success" name="action:GuardarFormulario">Guardar Formulario</button>
    <button type="submit" class="btn btn-danger" name="action:BorrarFormulario">Borrar formulario</button>
}